export const WEIGHTS = [
  // { density: 1 },
  // { random: 1 },
  // { emptyTileCount: 1 },
  // { emptyTileFactor: 1 },
  // { edgeScore: 1 },
  // { cornerScore: 1 },
  // { adjacentEqualTileScore: 1 },
  // { emptyTileFactor: 1, adjacentEqualTileScore: 1 },
  // { emptyTileFactor: 1, density: 1 },
  // { emptyTileFactor: 1, density: 1 },
  // { edgeScore: 1, adjacentEqualTileScore: 1 },
  // { density: 1, adjacentEqualTileScore: 1 },
  // { emptyTileFactor: 1, edgeScore: 1 },
  // {
  //   emptyTileFactor: 1,
  //   density: 1,
  //   edgeScore: 1,
  //   adjacentEqualTileScore: 1,
  // },
  // { emptyTileFactor: Math.random(), density: Math.random(), edgeScore: Math.random() },
  // { emptyTileFactor: Math.random(), density: Math.random(), edgeScore: Math.random() },
  // { emptyTileFactor: Math.random(), density: Math.random(), edgeScore: Math.random() },
  // { emptyTileFactor: Math.random(), density: Math.random(), edgeScore: Math.random() },
  // { emptyTileFactor: Math.random(), density: Math.random(), edgeScore: Math.random() },

  { emptyTileFactor: 1, density: 1 },
  { emptyTileFactor: 10, density: 1 },
  { emptyTileFactor: 1, density: 10 },
  { emptyTileFactor: 2, density: 1 },
  { emptyTileFactor: 1, density: 2 },
  {
    emptyTileFactor: Math.random() + Math.random() * 10,
    density: Math.random() + Math.random() * 10,
  },
  {
    emptyTileFactor: Math.random() + Math.random() * 10,
    density: Math.random() + Math.random() * 10,
  },
  {
    emptyTileFactor: Math.random() + Math.random() * 10,
    density: Math.random() + Math.random() * 10,
  },
  {
    emptyTileFactor: Math.random() + Math.random() * 10,
    density: Math.random() + Math.random() * 10,
  },
  {
    emptyTileFactor: Math.random() + Math.random() * 10,
    density: Math.random() + Math.random() * 10,
  },

  // {
  //   emptyTileFactor: Math.random() + Math.random() * 10,
  //   density: Math.random() + Math.random() * 10,
  //   edgeScore: Math.random() + Math.random() * 10,
  //   adjacentEqualTileScore: Math.random() + Math.random() * 10,
  // },
  // {
  //   emptyTileFactor: Math.random() + Math.random() * 10,
  //   density: Math.random() + Math.random() * 10,
  //   edgeScore: Math.random() + Math.random() * 10,
  //   adjacentEqualTileScore: Math.random() + Math.random() * 10,
  // },
  // {
  //   emptyTileFactor: Math.random() + Math.random() * 10,
  //   density: Math.random() + Math.random() * 10,
  //   edgeScore: Math.random() + Math.random() * 10,
  //   adjacentEqualTileScore: Math.random() + Math.random() * 10,
  // },
  // {
  //   emptyTileFactor: Math.random() + Math.random() * 10,
  //   density: Math.random() + Math.random() * 10,
  //   edgeScore: Math.random() + Math.random() * 10,
  //   cornerScore: Math.random() + Math.random() * 10,
  //   adjacentEqualTileScore: Math.random() + Math.random() * 10,
  // },
  // {
  //   emptyTileFactor: Math.random() + Math.random() * 10,
  //   density: Math.random() + Math.random() * 10,
  //   edgeScore: Math.random() + Math.random() * 10,
  //   cornerScore: Math.random() + Math.random() * 10,
  //   adjacentEqualTileScore: Math.random() + Math.random() * 10,
  // },
  // {
  //   emptyTileFactor: Math.random() + Math.random() * 10,
  //   density: Math.random() + Math.random() * 10,
  //   edgeScore: Math.random() + Math.random() * 10,
  //   cornerScore: Math.random() + Math.random() * 10,
  //   adjacentEqualTileScore: Math.random() + Math.random() * 10,
  // },
]
