export const WEIGHTS = [
  { density: 1 },
  { adjacencyScore: 1 },
  { emptyTileCount: 1 },
  { emptyTileFactor: 1 },
  { edgeScore: 1 },
  { cornerScore: 1 },
  { adjacentEqualTileScore: 1 },
  {
    density: Math.random(),
    adjacencyScore: Math.random(),
    emptyTileCount: Math.random(),
    emptyTileFactor: Math.random(),
    edgeScore: Math.random(),
    cornerScore: Math.random(),
    adjacentEqualTileScore: Math.random(),
  },
  // {
  //   density: 1,
  //   adjacencyScore: 1,
  //   emptyTileCount: 1,
  //   emptyTileFactor: 1,
  //   edgeScore: 1,
  //   cornerScore: 1,
  //   adjacentEqualTileScore: 1,
  // },
  // {
  //   density: 1,
  //   adjacencyScore: 1,
  //   emptyTileCount: 1,
  //   emptyTileFactor: 1,
  //   edgeScore: 1,
  //   cornerScore: 1,
  //   adjacentEqualTileScore: 1,
  // },
  // {
  //   density: 1,
  //   adjacencyScore: 1,
  //   emptyTileCount: 1,
  //   emptyTileFactor: 1,
  //   edgeScore: 1,
  //   cornerScore: 1,
  //   adjacentEqualTileScore: 1,
  // },
  // {
  //   density: 1,
  //   adjacencyScore: 1,
  //   emptyTileCount: 1,
  //   emptyTileFactor: 1,
  //   edgeScore: 1,
  //   cornerScore: 1,
  //   adjacentEqualTileScore: 1,
  // },
  // {
  //   density: 1,
  //   adjacencyScore: 1,
  //   emptyTileCount: 1,
  //   emptyTileFactor: 1,
  //   edgeScore: 1,
  //   cornerScore: 1,
  //   adjacentEqualTileScore: 1,
  // },
]
